applications:
  - name: cluster-config
    namespace: argocd
    project: default
    source:
      repoURL: https://github.com/eslam-fakhry/sample-terraform-kubernetes-argocd
      targetRevision: HEAD
      path: argocd/manifests/cluster
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        prune: false
        selfHeal: false